doc-valid-idents = [
  "OTel",
  "PyO3",
  ".."
]

allowed-duplicate-crates = [
  "base64",
  "bitflags",
  "getrandom",
  "hashbrown",
  "indexmap",
  "regex-automata",
  "regex-syntax",
  "socket2",
  "tracing-log",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc"
]
